### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by yedhrab** [tobiastimm/code-theme-converter#31]
Error at `npm\node_modules\code-theme-converter\dist\idea\convert.js:81:49` while converting theme

> I used this command: `code2idea https://github.com/yedhrab/DarkCode-Theme.git`

**Comment by tobiastimm** [comment]
I will take a look at `code2idea` next. Atm the sublime conversion was in my focus, but I will revisit the IDEA converter now. Thank you for reporting the issue!

**Comment by Zaknarfen** [comment]
I have the same error

**Comment by Zaknarfen** [comment]
I changed line 63 of the convert.js file to what shows in the image below and it seems to convert fine now.

![image](https://user-images.githubusercontent.com/4223973/124369088-64abdd00-dc3e-11eb-9d94-50af485ad78a.png)

**Comment by tobiastimm** [comment]
Since I'm not using the JetBrains IDEs on a daily basis, my time for digging into this is really limited. Can't tell you atm when this will be fixed

**Comment by Zaknarfen** [comment]
That change I made actually makes it work. I am using the Rider IDE from JetBrains and I could convert a color theme from VSCode to it. The only problem is that Rider won't recognize the files you generate with your library on import. I had to get a working color theme file (`.icls` file), open it with a text editor, and paste the contents of the theme `.xml` the library generated to me there.

In the end, I gave up because most of the colors were not translated to what I expected, so I had to manually create my theme. I was trying to get the Kimbie Dark from VSCode to Rider.
