### ISSUE TITLE
--as-tm-theme or -T option is ignored

### ISSUE THREAD

**Issue by adamhsparks** [tobiastimm/code-theme-converter#57]
I've tried using the `--as-tm-theme` and `-T` options. Neither one results in a tmTheme file.

```bash
code2subl git@github.com:enkia/tokyo-night-vscode-theme.git --as-tm-theme
Fetching repo
Converting 3 themes
🎉 Successfully converted the vscode theme for sublime text!
Converting Tokyo Night Light
Converting Tokyo Night
Converting Tokyo Night Storm
```

Results in

```bash
ls Tokyo\ Night\ Light/
Tokyo Night Light.sublime-color-scheme  Tokyo Night Light.sublime-theme
```

No matter what I do. Am I misunderstanding how to use this tool? I expected a  .tmTheme instead of .sublime-color-scheme as per the documentation.

**Comment by ArtAndreev** [comment]
It's fixed in master branch, but release isn't made. You can do the following:
1. clone the repo `git clone https://github.com/tobiastimm/code-theme-converter.git`;
1. `cd code-theme-converter`;
1. install node if you don't have it, run `npm i`;
1. `npm run build`;
1. `cd bin`
1. `./code2subl.js --as-tm-theme <your repo>`. The output will be there too.

**Comment by adamhsparks** [comment]
Thanks, but it doesn't appear to be fixed, I still have only Sublime theme files after installing from this repository and running the command in step 6 as suggested above.

```bash
❯ ls
Tokyo Night.sublime-color-scheme  Tokyo Night.sublime-theme
```
